version: '3'
services:
  db:
    image: 'postgres:latest'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3432:5432
  wanted_labs_demo:
    image: 'wantedlabs'
    depends_on:
      - db
    ports:
      - 5000:5000
    environment:
      DB_URL: 'postgresql://postgres:${DB_PASSWORD}@db:5432/postgres'
      POPULATE_DATABASE: True
      DROP_TABLES_AT_START: True
    command: ["./wait-for-it.sh", "db:5432", "--", "python", "./src/app.py"]